# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: hcloud-talos
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/airfocusio/{{ .ProjectName }}:latest-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/airfocusio/{{ .ProjectName }}:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/airfocusio/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/airfocusio/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/airfocusio/{{ .ProjectName }}:latest-amd64
      - ghcr.io/airfocusio/{{ .ProjectName }}:latest-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "0.0.0-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
