name: release
on:
 push:
    tags:
    - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: airfocusio
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        distribution: goreleaser
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
