name: test-e2e
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
concurrency:
  group: test
env:
  GO111MODULE: on
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        version:
          - talos: 1.2.6
            kubernetes: 1.23.13
          - talos: 1.2.6
            kubernetes: 1.24.7
          - talos: 1.2.6
            kubernetes: 1.25.3
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: Build sources
      run: go build ./...
    - name: Run tests e2e
      run: go test -v $(go list ./... | grep e2etests) -timeout 60m
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TALOS_VERSION: ${{ matrix.version.talos }}
        KUBERNETES_VERSION: ${{ matrix.version.kubernetes }}
