name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: Install talosctl
      run: |
        mkdir -p $HOME/bin
        wget -qO $HOME/bin/talosctl https://github.com/siderolabs/talos/releases/download/v1.2.6/talosctl-linux-amd64
        chmod +x $HOME/bin/talosctl
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: go test -v -timeout 60m ./...
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
