name: test-e2e
on:
  pull_request:
    branches:
    - main
concurrency:
  group: test
env:
  GO111MODULE: on
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        version:
          - talos: 1.6.8
            kubernetes: 1.29.8
          - talos: 1.7.6
            kubernetes: 1.30.4
    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: 1.22.x
    - uses: actions/checkout@v4
    - name: Build sources
      run: go build ./...
    - name: Run tests e2e
      run: go test -v $(go list ./... | grep e2etests) -timeout 60m
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TALOS_VERSION: ${{ matrix.version.talos }}
        KUBERNETES_VERSION: ${{ matrix.version.kubernetes }}
