name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: Build sources
      run: go build ./...
    - name: Run tests
      run: go test -v $(go list ./... | grep -v e2etests)
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        talos-version: [1.1.2, 1.2.6]
        kubernetes-version: [1.24.7]
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: actions/checkout@v2
    - name: Install talosctl
      run: |
        mkdir -p $HOME/bin
        wget -qO $HOME/bin/talosctl https://github.com/siderolabs/talos/releases/download/v${{ matrix.talos-version }}/talosctl-linux-amd64
        chmod +x $HOME/bin/talosctl
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Build sources
      run: go build ./...
    - name: Run tests e2e
      run: go test -v $(go list ./... | grep e2etests) -timeout 60m
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        TALOS_VERSION: ${{ matrix.talos-version }}
        KUBERNETES_VERSION: ${{ matrix.kubernetes-version }}
